CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE partners (
  id VARCHAR PRIMARY KEY,
  trading_name VARCHAR NOT NULL,
  owner_name VARCHAR NOT NULL,
  document VARCHAR UNIQUE NOT NULL,
  coverage_area GEOGRAPHY(MULTIPOLYGON,4326),
  address GEOGRAPHY(POINT,4326)
);